version: '3.9'

services:
  db:
    image: postgres:13.0-alpine
    restart: unless-stopped
    volumes:
      - db_value:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432

  web:
    restart: always
    build:
      context: .
      dockerfile: ./infra/Dockerfile
    container_name: 'app_django'
    volumes:
      - static_value:/app/lesta/static/
      - media_value:/app/lesta/media/
    ports:
      - '8000:8000'
    environment:
      DEBUG: "True"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      DJANGO_DB: postgresql
      POSTGRES_HOST: db
      POSTGRES_NAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
    depends_on:
      - db

  nginx:
    restart: always
    container_name: 'app_nginx'
    image: nginx:1.23-alpine
    ports:
      - 80:80
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/app/lesta/static/
      - media_value:/app/lesta/media/
    depends_on:
      - web

  redis:
    image: redis
    restart: always
    container_name: 'app_redis'
    command: redis-server
    ports:
      - '6379:6379'
    depends_on:
      - web

  celery:
    build:
      context: .
      dockerfile: ./infra/Dockerfile
    container_name: 'app_celery'
    command: celery -A lesta worker --loglevel=info --concurrency 1 -E
    volumes:
      - static_value:/app/lesta/static/
      - media_value:/app/lesta/media/
    environment:
      DEBUG: "True"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      DJANGO_DB: postgresql
      POSTGRES_HOST: db
      POSTGRES_NAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
    links:
      - redis
    depends_on:
      - web
      - redis

volumes:
  db_value:
  static_value:
  media_value: