# Generated by Django 4.2.11 on 2024-04-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/', verbose_name='Файл')),
                ('upload_at', models.DateTimeField(auto_now_add=True, verbose_name='Время загрузки')),
                ('processed', models.BooleanField(default=False, verbose_name='Статус загрузки')),
                ('words_list', models.TextField(verbose_name='50 наиболее частых слов')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
