# Generated by Django 4.2.11 on 2024-04-12 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/', verbose_name='Файл')),
                ('name', models.TextField(verbose_name='Название документа')),
                ('upload_at', models.DateTimeField(auto_now_add=True, verbose_name='Время загрузки')),
                ('quantity', models.IntegerField(default=0, null=True, verbose_name='Количество слов')),
                ('processed', models.BooleanField(default=False, verbose_name='Статус загрузки')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words_list', models.TextField(verbose_name='50 наиболее частых слов')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='text_app.file', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Слова',
                'verbose_name_plural': 'Слова',
            },
        ),
    ]
