# Generated by Django 4.2.11 on 2024-04-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.TextField(default=3, verbose_name='Название документа'),
            preserve_default=False,
        ),
    ]
