# Generated by Django 4.2.11 on 2024-04-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_app', '0002_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='quantity',
            field=models.IntegerField(default=100, verbose_name='Количество слов'),
            preserve_default=False,
        ),
    ]
