# Generated by Django 4.2.11 on 2024-04-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_app', '0003_file_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='quantity',
            field=models.IntegerField(null=True, verbose_name='Количество слов'),
        ),
    ]
