# Generated by Django 4.2.11 on 2024-04-09 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text_app', '0004_alter_file_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='file',
            name='words_list',
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True, verbose_name='Количество слов')),
                ('words_list', models.TextField(verbose_name='50 наиболее частых слов')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='text_app.file', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Слова',
                'verbose_name_plural': 'Слова',
            },
        ),
    ]
