# Generated by Django 4.2.11 on 2024-04-11 17:57

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('text_app', '0005_remove_file_quantity_remove_file_words_list_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='words_list',
            field=jsonfield.fields.JSONField(verbose_name='50 наиболее частых слов'),
        ),
    ]
