# Generated by Django 4.2.11 on 2024-04-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_app', '0006_alter_words_words_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='words_list',
            field=models.TextField(verbose_name='50 наиболее частых слов'),
        ),
    ]
